#!/bin/bash
# Quick setup script - generates copy-paste commands

echo "════════════════════════════════════════════════════════════"
echo "  Epic RPG - Database Setup Guide"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "📋 STEP 1: Open Supabase SQL Editor"
echo "   → https://supabase.com/dashboard/project/YOUR_PROJECT/sql-editor"
echo ""
echo "📋 STEP 2: Execute files in this ORDER:"
echo ""
echo "   ┌─────────────────────────────────────────────────────┐"
echo "   │ 1️⃣  Click 'Query' → 'New query'                    │"
echo "   │ 2️⃣  Copy ALL content from: supabase/01-schema.sql  │"
echo "   │ 3️⃣  Paste and press 'Run' (or Ctrl+Enter)           │"
echo "   └─────────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────────┐"
echo "   │ 4️⃣  Create NEW query                               │"
echo "   │ 5️⃣  Copy ALL content from: supabase/03-functions.sql │"
echo "   │ 6️⃣  Paste and press 'Run'                          │"
echo "   └─────────────────────────────────────────────────────┘"
echo ""
echo "   ┌─────────────────────────────────────────────────────┐"
echo "   │ 7️⃣  Create NEW query                               │"
echo "   │ 8️⃣  Copy ALL content from: supabase/04-seed.sql   │"
echo "   │ 9️⃣  Paste and press 'Run'                          │"
echo "   └─────────────────────────────────────────────────────┘"
echo ""
echo "════════════════════════════════════════════════════════════"
echo "  Verification Commands (run after setup)"
echo "════════════════════════════════════════════════════════════"
echo ""
echo "-- Verify tables created:"
echo "SELECT table_name FROM information_schema.tables"
echo "  WHERE table_schema = 'public';"
echo ""
echo "-- Verify functions:"
echo "SELECT proname FROM pg_proc"
echo "  WHERE pronamespace = 'public'::regnamespace;"
echo ""
echo "-- Verify data:"
echo "SELECT COUNT(*) as jobs FROM jobs;"
echo "SELECT COUNT(*) as skills FROM skills;"
echo "SELECT COUNT(*) as weapons FROM weapons;"
echo ""
echo "════════════════════════════════════════════════════════════"
echo ""
echo "✅ Setup complete! The game is ready to use."